import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ============================
# SKILL DATABASE (REAL SKILLS ONLY)
# ============================
SKILLS_DB = {
    "python", "numpy", "pandas", "scikit-learn",
    "tensorflow", "pytorch",
    "machine learning", "deep learning",
    "data analysis", "data cleaning",
    "feature engineering",
    "sql", "power bi", "tableau",
    "linux", "aws", "splunk",
    "excel", "api", "automation"
}

# ============================
# CLEAN TEXT
# ============================
def clean(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9 ]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

# ============================
# SKILL MATCHING
# ============================
def extract_skills(resume_text, jd_text):

    resume = clean(resume_text)
    jd = clean(jd_text)

    matched = []
    missing = []

    for skill in SKILLS_DB:
        if skill in resume and skill in jd:
            matched.append(skill)
        elif skill in jd and skill not in resume:
            missing.append(skill)

    return matched, missing

# ============================
# REASONING ENGINE (UPGRADED FOR HACKATHON)
# ============================
def generate_reasoning(score, matched, missing):

    # ---------------------------
    # MATCH LEVEL
    # ---------------------------
    if score >= 70:
        level = "High Match"
        summary = "Your profile strongly aligns with most of the job requirements."
        hiring_signal = "Shortlist Ready"
    elif score >= 40:
        level = "Moderate Match"
        summary = "Your profile partially matches the job requirements with some key gaps."
        hiring_signal = "Needs Skill Improvement"
    else:
        level = "Low Match"
        summary = "Your profile does not strongly match this role yet."
        hiring_signal = "Not Job Ready"

    # ---------------------------
    # STRENGTHS
    # ---------------------------
    strengths = matched[:6] if matched else ["Basic technical exposure in IT systems"]

    # ---------------------------
    # GAPS
    # ---------------------------
    gaps = missing[:6] if missing else ["No major technical gaps detected"]

    # ---------------------------
    # PRIORITY LEARNING
    # ---------------------------
    priority_learning = missing[:3] if missing else []

    # ---------------------------
    # INSIGHT (AI STYLE EXPLANATION)
    # ---------------------------
    insight = (
        f"The ATS score is mainly influenced by {len(matched)} matched skills "
        f"and {len(missing)} missing key job requirements. "
        "Improving core missing skills will significantly increase job compatibility."
    )

    # ---------------------------
    # FOCUS NOTE
    # ---------------------------
    if len(missing) > len(matched):
        focus_note = "Prioritize core technical skills before advanced topics."
    else:
        focus_note = "Strengthen real-world projects to enhance job readiness."

    return {
        "level": level,
        "summary": summary,
        "hiring_signal": hiring_signal,

        "strengths": strengths,
        "gaps": gaps,

        "priority_learning": priority_learning,
        "focus_note": focus_note,
        "insight": insight,

        "recommendation": "Build 1–2 hands-on projects using missing skills to improve job readiness."
    }

# ============================
# MAIN FUNCTION
# ============================
def analyze_resume(resume_text, job_description):

    resume_clean = clean(resume_text)
    jd_clean = clean(job_description)

    # ATS SCORE (TF-IDF)
    vectorizer = TfidfVectorizer()
    vectors = vectorizer.fit_transform([resume_clean, jd_clean])

    similarity = cosine_similarity(vectors[0:1], vectors[1:2])[0][0]
    score = round(similarity * 100, 2)

    # SKILLS
    matched, missing = extract_skills(resume_text, job_description)

    # REASONING LAYER (UPGRADED)
    reasoning = generate_reasoning(score, matched, missing)

    return {
        "score": score,
        "matched": matched,
        "missing": missing,

        # HACKATHON AI LAYER
        "reasoning": reasoning,

        "cover_letter": "Generated by AI module",
        "linkedin_summary": "Generated by AI module",

        "interview_questions": [
            "Explain your experience in Linux troubleshooting",
            "How do you handle system incidents?",
            "What automation scripts have you written?"
        ]
    }
