import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ============================
# SIMPLE SKILL DATABASE
# ============================
SKILLS_DB = {
    "python", "numpy", "pandas", "scikit-learn",
    "tensorflow", "pytorch",
    "machine learning", "data cleaning",
    "feature engineering",
    "sql", "power bi", "tableau",
    "linux", "aws", "api"
}

# ============================
# CLEAN TEXT FUNCTION
# ============================
def clean(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9 ]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

# ============================
# SKILL EXTRACTION
# ============================
def extract_skills(resume_text, jd_text):
    resume = clean(resume_text)
    jd = clean(jd_text)

    matched = []
    missing = []

    for skill in SKILLS_DB:
        if skill in resume and skill in jd:
            matched.append(skill)
        elif skill in jd and skill not in resume:
            missing.append(skill)

    return matched, missing

# ============================
# REASONING LAYER (UPGRADED CORE)
# ============================
def generate_reasoning(score, matched, missing):

    if score >= 70:
        level = "Strong Match"
        summary = "Good alignment with job requirements."
    elif score >= 40:
        level = "Moderate Match"
        summary = "Partial match. Some key skills missing."
    else:
        level = "Low Match"
        summary = "Major skill gaps detected."

    strengths = matched[:5] if matched else ["Basic technical exposure"]
    gaps = missing[:5] if missing else ["No major gaps detected"]

    if len(missing) > len(matched):
        recommendation = "Focus on missing core ML and data skills."
    else:
        recommendation = "Strengthen practical project experience."

    return {
        "level": level,
        "summary": summary,
        "strengths": strengths,
        "gaps": gaps,
        "recommendation": recommendation
    }

# ============================
# MAIN ANALYSIS ENGINE
# ============================
def analyze_resume(resume_text, job_description):

    resume_clean = clean(resume_text)
    jd_clean = clean(job_description)

    # ATS SCORE
    vectorizer = TfidfVectorizer()
    vectors = vectorizer.fit_transform([resume_clean, jd_clean])

    score = round(
        cosine_similarity(vectors[0:1], vectors[1:2])[0][0] * 100,
        2
    )

    # SKILL MATCH
    matched, missing = extract_skills(resume_text, job_description)

    # REASONING LAYER
    reasoning = generate_reasoning(score, matched, missing)

    return {
        "score": score,
        "matched": matched,
        "missing": missing,

        # 🔥 NEW UPGRADE FOR HACKATHON
        "reasoning": reasoning,

        "cover_letter": "Generated by AI module",
        "linkedin_summary": "Generated by AI module",
        "interview_questions": [
            "Explain your experience in Linux troubleshooting",
            "How do you handle system incidents?",
            "What automation scripts have you written?"
        ]
    }
