import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ============================
# SIMPLE SKILL DATABASE
# ============================
SKILLS_DB = {
    "python", "numpy", "pandas", "scikit-learn",
    "tensorflow", "pytorch",
    "machine learning", "data cleaning",
    "feature engineering",
    "sql", "power bi", "tableau",
    "linux", "aws", "api"
}

# ============================
# CLEAN TEXT FUNCTION
# ============================
def clean(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9 ]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

# ============================
# SKILL EXTRACTION
# ============================
def extract_skills(resume_text, jd_text):
    resume = clean(resume_text)
    jd = clean(jd_text)

    matched = []
    missing = []

    for skill in SKILLS_DB:
        if skill in resume and skill in jd:
            matched.append(skill)
        elif skill in jd and skill not in resume:
            missing.append(skill)

    return matched, missing

# ============================
# REASONING LAYER (UPGRADED CORE)
# ============================
def generate_reasoning(score, matched, missing):

    # -----------------------------
    # 1. ROLE FIT LOGIC (UPGRADED)
    # -----------------------------
    if score >= 75:
        level = "High Job Fit"
        summary = "Strong alignment with job requirements."
    elif score >= 50:
        level = "Moderate Job Fit"
        summary = "Good potential but skill gaps exist."
    else:
        level = "Low Job Fit"
        summary = "Significant gap between profile and role."

    # -----------------------------
    # 2. GAP CLASSIFICATION (NEW)
    # -----------------------------
    critical_skills = {"numpy", "pandas", "scikit-learn", "tensorflow", "pytorch"}
    important_skills = {"feature engineering", "api", "sql"}

    critical_gaps = []
    important_gaps = []
    minor_gaps = []

    for skill in missing:
        if skill in critical_skills:
            critical_gaps.append(skill)
        elif skill in important_skills:
            important_gaps.append(skill)
        else:
            minor_gaps.append(skill)

    # -----------------------------
    # 3. STRENGTH INTELLIGENCE (UPGRADED)
    # -----------------------------
    strengths = matched[:6] if matched else ["Basic technical exposure"]

    # -----------------------------
    # 4. SMART RECOMMENDATION ENGINE
    # -----------------------------
    if critical_gaps:
        recommendation = "Prioritize learning core ML libraries (NumPy, Pandas, Scikit-learn) before applying."
    elif important_gaps:
        recommendation = "Improve feature engineering and API deployment skills for better job readiness."
    elif len(matched) >= 5:
        recommendation = "Start applying while building real ML projects."
    else:
        recommendation = "Strengthen fundamentals and build hands-on projects."

    # -----------------------------
    # 5. CAREER INSIGHT (NEW LAYER)
    # -----------------------------
    if "python" in matched and len(critical_gaps) <= 2:
        career_signal = "Strong transition candidate from IT to ML"
    else:
        career_signal = "Needs structured ML upskilling path"

    # -----------------------------
    # FINAL OUTPUT
    # -----------------------------
    return {
        "level": level,
        "summary": summary,

        "strengths": strengths,

        "critical_gaps": critical_gaps,
        "important_gaps": important_gaps,
        "minor_gaps": minor_gaps,

        "recommendation": recommendation,

        # 🔥 THIS IS YOUR HACKATHON DIFFERENTIATOR
        "career_signal": career_signal
    }
# ============================
# MAIN ANALYSIS ENGINE
# ============================
def analyze_resume(resume_text, job_description):

    resume_clean = clean(resume_text)
    jd_clean = clean(job_description)

    # ATS SCORE
    vectorizer = TfidfVectorizer()
    vectors = vectorizer.fit_transform([resume_clean, jd_clean])

    score = round(
        cosine_similarity(vectors[0:1], vectors[1:2])[0][0] * 100,
        2
    )

    # SKILL MATCH
    matched, missing = extract_skills(resume_text, job_description)

    # REASONING LAYER
    reasoning = generate_reasoning(score, matched, missing)

    return {
        "score": score,
        "matched": matched,
        "missing": missing,

        # 🔥 NEW UPGRADE FOR HACKATHON
        "reasoning": reasoning,

        "cover_letter": "Generated by AI module",
        "linkedin_summary": "Generated by AI module",
        "interview_questions": [
            "Explain your experience in Linux troubleshooting",
            "How do you handle system incidents?",
            "What automation scripts have you written?"
        ]
    }
